
permalink: /:title/
http://ivetteaddington.com

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

gems:
   - jekyll-redirect-from

  # -
  #   scope:
  #     path: ""
  #   values:
  #     lang: en
  #     layout: default
  # -
  #   scope:
  #     path: _posts/es
  #   values:
  #     lang: es
  # -
  #   scope:
  #     path: _posts/es/pages
  #   values:
  #     type: pages
  # -
  #   scope:
  #     path: _posts/en/pages
  #   values:
  #     type: pages
  # -
  #   scope:
  #     path: _posts/es/projects
  #   values:
  #     type: projects
  # -
  #   scope:
  #     path: _posts/en/projects
  #   values:
  #     type: projects

  # -
  #   scope:
  #     path: _posts/es/posts
  #   values:
  #     type: posts
  # -
  #   scope:
  #     path: _posts/en/posts
  #   values:
  #     type: posts



































